import type { ForgeLoreSection } from '../../services/api/ForgeApiService.js';
import { forgeApi } from '../../services/api/ForgeApiService.js';
import { localeService } from '../../services/i18n/locale-service.js';
import type { LoreSection } from '../platform/LoreScroll.js';

/**
 * Fetch raw lore sections from the API (all language fields).
 * Falls back to null if the API call fails or returns empty.
 */
export async function fetchRawLoreSections(simulationId: string): Promise<ForgeLoreSection[] | null> {
  try {
    const resp = await forgeApi.getSimulationLore(simulationId);
    if (!resp.success || !resp.data || !Array.isArray(resp.data) || resp.data.length === 0) {
      return null;
    }
    return resp.data;
  } catch {
    return null;
  }
}

/**
 * Returns true if the section is a classified dossier section (generated by feature purchase).
 */
export function isClassifiedSection(section: ForgeLoreSection): boolean {
  return section.chapter === 'CLASSIFIED' || section.sort_order >= 100;
}

/**
 * Map raw API lore sections to display-ready LoreSection[] using current locale.
 */
export function mapLoreSectionsForLocale(raw: ForgeLoreSection[]): LoreSection[] {
  const useDe = localeService.currentLocale !== 'en';
  return raw.map((s) => ({
    id: s.id,
    chapter: s.chapter,
    arcanum: s.arcanum,
    title: (useDe && s.title_de) || s.title,
    epigraph: (useDe && s.epigraph_de) || s.epigraph || '',
    body: (useDe && s.body_de) || s.body,
    imageSlug: s.image_slug ?? undefined,
    imageCaption: (useDe && s.image_caption_de) || s.image_caption || undefined,
  }));
}
