"""Ops cost forecast service (P3.1).

End-of-month projection + NL driver text for the Bureau Ops ForecastPanel.

AD-6: the server computes the baseline projection (linear + seasonal from
the 30-day rollup) once per panel-open; client sliders modify the baseline
locally for <100ms response. Natural-language driver text is generated by
Haiku (cheap, ~$0.002/call) and cached 5 minutes per snapshot shape.

Budget exemption (AD-6):
    Haiku calls intentionally omit ``admin_supabase`` from ``run_ai`` so
    ``BudgetEnforcementService.pre_check`` is skipped — the monitoring
    surface must not be blocked by the system it monitors. A Haiku failure
    is logged at warning and falls back to a static driver line; the
    5-minute cache absorbs repeated panel-opens without re-trying. There
    is no circuit-breaker integration on the run_ai path (the breaker
    only wraps the raw OpenRouterService HTTP path), so the graceful
    fallback IS the recursion-prevention mechanism.
"""

from __future__ import annotations

import asyncio
import hashlib
import logging
import math
import statistics
import time
from datetime import UTC, date, datetime, timedelta
from typing import Any, Final

from pydantic_ai import Agent

from backend.models.bureau_ops import ForecastProjection, ForecastSlider
from backend.services.ai_utils import get_openrouter_model, run_ai
from backend.utils.responses import extract_list
from supabase import AsyncClient as Client

logger = logging.getLogger(__name__)

# AD-6: Haiku — cheap NL synthesis. Hardcoded here rather than wired
# through platform_model_config because the forecast service is the only
# caller; keeping it self-contained avoids polluting the shared model
# settings surface with a one-off purpose.
_FORECAST_MODEL: Final[str] = "anthropic/claude-haiku-4.5"
_FORECAST_PURPOSE: Final[str] = "ops_forecast"
_DRIVER_TEXT_TTL_S: Final[float] = 5 * 60.0
_DRIVER_TEXT_TIMEOUT_S: Final[float] = 15.0
_LOOKBACK_DAYS: Final[int] = 30
_TOP_PURPOSE_COUNT: Final[int] = 3

# What-if slider catalog. Keys are the contract surface ForecastPanel uses
# to map slider deltas to per-purpose adjustments client-side. Adding a
# slider here makes it appear in the UI on next refresh.
_DEFAULT_SLIDERS: Final[list[ForecastSlider]] = [
    ForecastSlider(
        key="growth_multiplier",
        label="User growth scenario",
        min=0.5,
        max=2.0,
        default=1.0,
        unit="x",
    ),
    ForecastSlider(
        key="forge_runs_pct",
        label="Forge ignites vs current",
        min=0,
        max=300,
        default=100,
        unit="%",
    ),
    ForecastSlider(
        key="heartbeat_pct",
        label="Heartbeat frequency",
        min=50,
        max=200,
        default=100,
        unit="%",
    ),
    ForecastSlider(
        key="chat_pct",
        label="Chat volume",
        min=0,
        max=300,
        default=100,
        unit="%",
    ),
    ForecastSlider(
        key="model_efficiency_pct",
        label="Avg model cost (Haiku ↔ Sonnet)",
        min=20,
        max=200,
        default=100,
        unit="%",
    ),
]

# ── Driver-text cache ────────────────────────────────────────────────────

_driver_text_cache: dict[str, tuple[str, float]] = {}


def _cache_get(key: str) -> str | None:
    cached = _driver_text_cache.get(key)
    if cached is None:
        return None
    text, expires_at = cached
    if time.monotonic() >= expires_at:
        return None
    return text


def _cache_put(key: str, text: str) -> None:
    _driver_text_cache[key] = (text, time.monotonic() + _DRIVER_TEXT_TTL_S)


def reset_driver_text_cache() -> None:
    """Drop the driver-text cache. Test-only seam.

    Production code should never call this — the cache is fail-safe and
    self-expiring. Tests override it to make assertions deterministic.
    """
    global _driver_text_cache  # noqa: PLW0603 — module-level cache by design
    _driver_text_cache = {}


# ── Service ──────────────────────────────────────────────────────────────


class OpsForecastService:
    """Forecast projection + NL driver text for the Bureau Ops panel."""

    @classmethod
    async def project(cls, admin_supabase: Client) -> ForecastProjection:
        """Return the end-of-month projection + driver text + slider catalog.

        Single endpoint surface — the client polls this on panel-open and
        applies slider deltas locally via a fixed formula. The 30-day
        materialized view drives both the projection math and the
        driver-text prompt.
        """
        rows = await cls._fetch_rollup(admin_supabase)
        snapshot = cls._build_snapshot(rows)
        driver_text = await cls._driver_text(snapshot)
        return ForecastProjection(
            projected_usd=snapshot["projected_usd"],
            confidence_low_usd=snapshot["confidence_low_usd"],
            confidence_high_usd=snapshot["confidence_high_usd"],
            days_remaining=snapshot["days_remaining"],
            driver_text=driver_text,
            sliders=list(_DEFAULT_SLIDERS),
            generated_at=datetime.now(UTC),
        )

    # ── Snapshot assembly ───────────────────────────────────────────────

    @staticmethod
    async def _fetch_rollup(admin_supabase: Client) -> list[dict[str, Any]]:
        """Pull last 30 days of (hour, purpose, usd, calls) rows from the MV.

        The materialized view is refreshed every 60s by the rollup
        scheduler (see ``ai_usage_rollup_scheduler``). A panel that opens
        within 60s of new spend may see a slightly stale projection — the
        next refresh corrects it, and the daily-resolution math here is
        not sensitive to single-hour gaps.
        """
        since = (datetime.now(UTC) - timedelta(days=_LOOKBACK_DAYS)).isoformat()
        resp = await (
            admin_supabase.table("ai_usage_rollup_hour")
            .select("hour, purpose, calls, usd")
            .gte("hour", since)
            .order("hour", desc=False)
            .execute()
        )
        return extract_list(resp)

    @classmethod
    def _build_snapshot(cls, rows: list[dict[str, Any]]) -> dict[str, Any]:
        """Compute baseline projection from rollup rows.

        Linear: ``mtd + daily_mean * days_remaining``.
        Seasonal: ``mtd + sum(daily_mean * dow_mult[d] for d in remaining)``.
        Confidence band: ``± stdev * sqrt(days_remaining)`` (independent
        daily samples; degrades gracefully on the last day to ±0).

        Today's partial spend is rolled into MTD as-is — the projection
        slightly underestimates early in the day and corrects through
        the day. Within-day refinement is deferred (would require an
        intraday spend curve we don't yet model).
        """
        now = datetime.now(UTC)
        today = now.date()
        per_day: dict[date, float] = {}
        per_purpose_30d: dict[str, float] = {}
        for row in rows:
            hour_dt = _parse_hour(row.get("hour"))
            if hour_dt is None:
                continue
            day = hour_dt.date()
            usd = float(row.get("usd") or 0.0)
            per_day[day] = per_day.get(day, 0.0) + usd
            purpose = str(row.get("purpose") or "unknown")
            per_purpose_30d[purpose] = per_purpose_30d.get(purpose, 0.0) + usd

        # Day-of-week multipliers
        dow_buckets: dict[int, list[float]] = {i: [] for i in range(7)}
        for day, usd in per_day.items():
            dow_buckets[day.weekday()].append(usd)
        all_daily = list(per_day.values())
        overall_mean = statistics.fmean(all_daily) if all_daily else 0.0
        dow_mult: dict[int, float] = {}
        for dow, samples in dow_buckets.items():
            if samples and overall_mean > 0:
                dow_mult[dow] = statistics.fmean(samples) / overall_mean
            else:
                dow_mult[dow] = 1.0
        daily_stdev = statistics.stdev(all_daily) if len(all_daily) >= 2 else 0.0

        # Month boundaries
        month_start = today.replace(day=1)
        if month_start.month == 12:
            next_month = month_start.replace(year=month_start.year + 1, month=1)
        else:
            next_month = month_start.replace(month=month_start.month + 1)
        days_in_month = (next_month - month_start).days
        days_elapsed = (today - month_start).days  # today is day (elapsed + 1)
        days_remaining = max(0, days_in_month - days_elapsed - 1)

        mtd_usd = sum(usd for day, usd in per_day.items() if day >= month_start)

        # Seasonal projection — sum each remaining day weighted by its DOW
        # multiplier so a Friday-heavy 2-week tail projects higher than a
        # Sunday-heavy one with the same daily mean.
        remaining_dates = [today + timedelta(days=i + 1) for i in range(days_remaining)]
        seasonal_extra = sum(
            overall_mean * dow_mult.get(d.weekday(), 1.0) for d in remaining_dates
        )
        projected_usd = mtd_usd + seasonal_extra
        linear_extra = overall_mean * days_remaining

        ci_half = (
            daily_stdev * math.sqrt(days_remaining) if days_remaining > 0 else 0.0
        )

        sorted_purposes = sorted(
            per_purpose_30d.items(),
            key=lambda kv: kv[1],
            reverse=True,
        )[:_TOP_PURPOSE_COUNT]
        total_30d = sum(per_purpose_30d.values()) or 1.0
        top_purposes = [
            {
                "purpose": purpose,
                "usd_30d": round(usd, 4),
                "pct": round(usd / total_30d * 100, 1),
            }
            for purpose, usd in sorted_purposes
        ]

        return {
            "mtd_usd": round(mtd_usd, 4),
            "days_elapsed": days_elapsed,
            "days_remaining": days_remaining,
            "linear_projected_usd": round(mtd_usd + linear_extra, 4),
            "projected_usd": round(projected_usd, 4),
            "confidence_low_usd": round(max(0.0, projected_usd - ci_half), 4),
            "confidence_high_usd": round(projected_usd + ci_half, 4),
            "daily_mean": round(overall_mean, 4),
            "daily_stdev": round(daily_stdev, 4),
            "top_purposes": top_purposes,
        }

    # ── NL driver text via Haiku ────────────────────────────────────────

    @classmethod
    async def _driver_text(cls, snapshot: dict[str, Any]) -> str:
        """Generate driver text via Haiku, cached 5 minutes.

        Cache key is a content-hash over the projection inputs that
        materially change the narrative (rounded to absorb noise from
        sub-cent fluctuations).
        """
        cache_key = _driver_cache_key(snapshot)
        cached = _cache_get(cache_key)
        if cached is not None:
            return cached

        text = await cls._call_haiku(snapshot)
        if text:
            _cache_put(cache_key, text)
            return text
        return cls._fallback_driver_text(snapshot)

    @staticmethod
    async def _call_haiku(snapshot: dict[str, Any]) -> str | None:
        """One Haiku call. Returns None on any failure (logged at warning).

        ``admin_supabase`` is intentionally omitted from ``run_ai`` —
        forecast generation is budget-exempt by design (AD-6).
        """
        try:
            agent = Agent(
                get_openrouter_model(model_id=_FORECAST_MODEL),
                system_prompt=(
                    "You are an ops analyst summarizing AI cost forecasts in 1-2 "
                    "sentences. Be specific about top drivers; no fluff; no "
                    "apology. Plain English, no markdown, no quotes."
                ),
                retries=1,
            )
            top_lines = (
                "\n".join(
                    f"  - {p['purpose']}: ${p['usd_30d']:.2f} "
                    f"({p['pct']:.0f}% of 30d spend)"
                    for p in snapshot["top_purposes"]
                )
                or "  - (no spend recorded in the last 30 days)"
            )
            ci_half = snapshot["confidence_high_usd"] - snapshot["projected_usd"]
            prompt = (
                f"Month-to-date: ${snapshot['mtd_usd']:.2f}\n"
                f"Projected end-of-month: ${snapshot['projected_usd']:.2f} "
                f"(±${ci_half:.2f})\n"
                f"Days remaining: {snapshot['days_remaining']}\n"
                f"Top purposes (last 30d):\n{top_lines}\n\n"
                "Summarize the projection and call out the 1-2 biggest cost "
                "drivers."
            )
            result = await asyncio.wait_for(
                run_ai(
                    agent,
                    prompt,
                    purpose=_FORECAST_PURPOSE,
                    # max_tokens=200 caps cost at ~$0.0001/call for the
                    # 1-2 sentence summary; timeout=10 bounds the upstream
                    # call cleanly so the outer wait_for is a backstop, not
                    # the primary deadline.
                    model_settings={"timeout": 10, "max_tokens": 200},
                    # admin_supabase intentionally omitted — see method docstring
                ),
                timeout=_DRIVER_TEXT_TIMEOUT_S,
            )
            text = str(getattr(result, "output", result)).strip()
            return text or None
        except Exception:  # noqa: BLE001 — driver text is best-effort
            logger.warning(
                "Forecast driver-text generation failed; falling back to static text",
                exc_info=True,
            )
            return None

    @staticmethod
    def _fallback_driver_text(snapshot: dict[str, Any]) -> str:
        """Static fallback when Haiku call fails or returns empty.

        Always present — the panel never renders without a driver line so
        the UX stays calm during provider outages. The fallback names the
        top purpose so operators still see attribution at a glance.
        """
        top = snapshot["top_purposes"]
        ci_half = snapshot["confidence_high_usd"] - snapshot["projected_usd"]
        if not top:
            return (
                f"Projected ${snapshot['projected_usd']:.2f} by month-end "
                f"({snapshot['days_remaining']} days remaining); "
                "no recent spend recorded."
            )
        leader = top[0]
        return (
            f"Projected ${snapshot['projected_usd']:.2f} by month-end "
            f"(±${ci_half:.2f}); {leader['purpose']} drives "
            f"{leader['pct']:.0f}% of recent spend."
        )


# ── Helpers ──────────────────────────────────────────────────────────────


def _driver_cache_key(snapshot: dict[str, Any]) -> str:
    """Stable key over inputs that materially affect the driver text.

    Rounded to dollars + integer percentages so successive panel-opens
    within the same projection neighborhood hit the same cache entry.
    """
    payload = (
        round(snapshot["projected_usd"], 0),
        round(snapshot["mtd_usd"], 0),
        snapshot["days_remaining"],
        tuple(
            (p["purpose"], int(p["pct"]))
            for p in snapshot["top_purposes"]
        ),
    )
    return hashlib.sha256(repr(payload).encode("utf-8")).hexdigest()


def _parse_hour(value: object) -> datetime | None:
    if isinstance(value, datetime):
        return value if value.tzinfo else value.replace(tzinfo=UTC)
    if isinstance(value, str):
        normalized = value.replace("Z", "+00:00") if value.endswith("Z") else value
        try:
            parsed = datetime.fromisoformat(normalized)
            return parsed if parsed.tzinfo else parsed.replace(tzinfo=UTC)
        except ValueError:
            return None
    return None
