"""Content-pack → SQL seed generator (clean rewrite).

Replaces `scripts/extract_dungeon_content_to_sql.py`. The rewrite addresses
six architectural problems in the legacy generator:

  1. Legacy: each table's column list was hand-written three times (INSERT,
     VALUES, UPDATE SET). Here: one `TableSpec` per table, templated once.
  2. Legacy: silent duplicate-ID rename (`banter_id = f"{banter_id}_dup{idx}"`)
     papered over a data bug. Here: duplicates cause the *validator* to
     fail loudly before the generator runs.
  3. Legacy: `_TIER_FIELD_FOR_ARCHETYPE` hard-coded inside the generator.
     Here: lives in `schemas.py` next to the data it describes.
  4. Legacy: no CLI surface, no dry-run, writes to a fixed path that does
     not match the migration naming scheme. Here: `--output`, `--stdout`,
     `--dry-run` — caller decides, generator is pure.
  5. Legacy: Python dicts were the generator's only input. Here: packs are
     the input, Python dicts are scheduled for deletion in A1.5.
  6. Legacy: no determinism guarantee. Here: sorted archetype iteration +
     `json.dumps(sort_keys=True)` yield byte-identical output across runs.

Usage:
    python -m backend.services.content_packs.generate_migration --stdout
    python -m backend.services.content_packs.generate_migration --output path/to/seed.sql
    python -m backend.services.content_packs.generate_migration --dry-run  # counts only
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Callable
from pathlib import Path

from backend.services.content_packs.loader import (
    DEFAULT_PACK_ROOT,
    PackLoadResult,
    load_packs,
)
from backend.services.content_packs.row_builders import (
    build_ability_rows,
    build_anchor_rows,
    build_banter_rows,
    build_barometer_rows,
    build_choice_rows,
    build_encounter_rows,
    build_enemy_rows,
    build_entrance_rows,
    build_loot_rows,
    build_spawn_rows,
)
from backend.services.content_packs.sql_primitives import SqlValue
from backend.services.content_packs.table_specs import (
    ABILITIES,
    ANCHOR_OBJECTS,
    BANTER,
    BAROMETER_TEXTS,
    EMISSION_ORDER,
    ENCOUNTER_CHOICES,
    ENCOUNTER_TEMPLATES,
    ENEMY_TEMPLATES,
    ENTRANCE_TEXTS,
    LOOT_ITEMS,
    SPAWN_CONFIGS,
    TableSpec,
)

# ── Dispatch: TableSpec → row builder ────────────────────────────────────

RowBuilder = Callable[[PackLoadResult], list[dict[str, SqlValue]]]

_BUILDER_FOR_SPEC: dict[TableSpec, RowBuilder] = {
    BANTER: build_banter_rows,
    ENEMY_TEMPLATES: build_enemy_rows,
    SPAWN_CONFIGS: build_spawn_rows,
    ENCOUNTER_TEMPLATES: build_encounter_rows,
    ENCOUNTER_CHOICES: build_choice_rows,
    LOOT_ITEMS: build_loot_rows,
    ANCHOR_OBJECTS: build_anchor_rows,
    ENTRANCE_TEXTS: build_entrance_rows,
    BAROMETER_TEXTS: build_barometer_rows,
    ABILITIES: build_ability_rows,
}


# ── Emission primitives ───────────────────────────────────────────────────


def emit_insert(spec: TableSpec, row: dict[str, SqlValue]) -> str:
    """Render one INSERT … ON CONFLICT … DO UPDATE SET statement."""
    missing = [c for c in spec.columns if c not in row]
    if missing:
        raise KeyError(f"{spec.name}: row missing columns {missing}")
    values = ", ".join(row[c].render() for c in spec.columns)
    return (
        f"INSERT INTO {spec.name} ({spec.insert_column_list}) VALUES ({values}) "
        f"ON CONFLICT {spec.conflict_target} DO UPDATE SET {spec.update_set_clause};"
    )


def emit_section(spec: TableSpec, result: PackLoadResult) -> tuple[list[str], int]:
    """Emit a header comment plus all INSERT rows for one table."""
    rows = _BUILDER_FOR_SPEC[spec](result)
    header = f"-- ── {spec.name} ({len(rows)} rows) "
    header += "─" * max(0, 78 - len(header))
    lines: list[str] = [header]
    lines.extend(emit_insert(spec, row) for row in rows)
    lines.append("")
    return lines, len(rows)


def generate_sql(result: PackLoadResult, *, truncate: bool = True) -> tuple[str, dict[str, int]]:
    """Produce the full seed SQL string plus a per-table row count map.

    `truncate=True` (default): emit a TRUNCATE ... RESTART IDENTITY CASCADE
    prefix so the migration fully replaces any existing seed content. This
    is the correct default for A1.5 because the legacy seed carries drift
    (e.g. `sb_30_dup0` banter IDs renamed to `sb_30b` in the pack) that
    plain UPSERT cannot resolve — stale rows would survive.

    `truncate=False`: pure additive mode for hypothetical future
    incremental migrations where ID-stability is guaranteed. Not used by
    A1.5 but preserved so the primitive exists.
    """
    counts: dict[str, int] = {}
    lines: list[str] = [
        "-- ============================================================================",
        "-- Dungeon content seed (generated from content/dungeon/**/*.yaml)",
        "-- Generated by backend/services/content_packs/generate_migration.py",
        "-- DO NOT EDIT MANUALLY. Re-run the generator to regenerate.",
        "-- ============================================================================",
        "",
        "BEGIN;",
        "",
    ]
    if truncate:
        truncate_targets = ", ".join(spec.name for spec in EMISSION_ORDER)
        lines.extend([
            "-- Clean slate: pack is the single source of truth, so drop any",
            "-- existing rows (including legacy `_dup{idx}` renames from the",
            "-- old extract script) before re-inserting from packs.",
            f"TRUNCATE TABLE {truncate_targets} RESTART IDENTITY CASCADE;",
            "",
        ])
    for spec in EMISSION_ORDER:
        section_lines, count = emit_section(spec, result)
        lines.extend(section_lines)
        counts[spec.name] = count
    lines.append("COMMIT;")
    lines.append("")
    return "\n".join(lines), counts


# ── CLI ───────────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate dungeon content seed SQL from YAML packs.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help=f"Pack root (defaults to {DEFAULT_PACK_ROOT}).",
    )
    output_mode = parser.add_mutually_exclusive_group()
    output_mode.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Write generated SQL to this file.",
    )
    output_mode.add_argument(
        "--stdout",
        action="store_true",
        help="Write generated SQL to stdout.",
    )
    output_mode.add_argument(
        "--dry-run",
        action="store_true",
        help="Load packs and count rows, but emit no SQL.",
    )
    parser.add_argument(
        "--no-truncate",
        action="store_true",
        help="Skip the TRUNCATE prefix (additive migration, ID-stability required).",
    )
    args = parser.parse_args(argv)

    result = load_packs(args.root)
    sql, counts = generate_sql(result, truncate=not args.no_truncate)

    if args.dry_run or (not args.output and not args.stdout):
        _print_counts(counts)
        return 0

    if args.stdout:
        sys.stdout.write(sql)
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(sql, encoding="utf-8")
    _print_counts(counts)
    print(f"Wrote {sum(counts.values())} rows to {args.output}")
    return 0


def _print_counts(counts: dict[str, int]) -> None:
    for table, n in counts.items():
        print(f"  {table:<30} {n:>5}")
    print(f"  {'TOTAL':<30} {sum(counts.values()):>5}")


if __name__ == "__main__":
    raise SystemExit(main())
