"""Generic seed-SQL emission: TableSpec + rows -> idempotent migration body.

Domain-agnostic core shared by the dungeon generator (`generate_migration`)
and the drift generator (`generate_drift_migration`). It knows only how to
turn a list of `(TableSpec, rows)` sections into a
`BEGIN; [TRUNCATE;] INSERT ... ON CONFLICT ...; COMMIT;` document. The domain
modules own loading and row building; this owns the SQL scaffolding and the
escape-safe INSERT rendering (via `sql_primitives`), so there is exactly one
place where a column-order or dollar-quoting bug could live.
"""

from __future__ import annotations

from backend.services.content_packs.sql_primitives import SqlValue
from backend.services.content_packs.table_specs import TableSpec

# One emitted table: its spec plus the pre-built rows for it.
Section = tuple[TableSpec, list[dict[str, SqlValue]]]


def emit_insert(spec: TableSpec, row: dict[str, SqlValue]) -> str:
    """Render one INSERT ... ON CONFLICT ... DO UPDATE SET statement."""
    missing = [c for c in spec.columns if c not in row]
    if missing:
        raise KeyError(f"{spec.name}: row missing columns {missing}")
    values = ", ".join(row[c].render() for c in spec.columns)
    return (
        f"INSERT INTO {spec.name} ({spec.insert_column_list}) VALUES ({values}) "
        f"ON CONFLICT {spec.conflict_target} DO UPDATE SET {spec.update_set_clause};"
    )


def render_section(spec: TableSpec, rows: list[dict[str, SqlValue]]) -> tuple[list[str], int]:
    """Emit a header comment plus all INSERT rows for one table."""
    header = f"-- ── {spec.name} ({len(rows)} rows) "
    header += "─" * max(0, 78 - len(header))
    lines: list[str] = [header]
    lines.extend(emit_insert(spec, row) for row in rows)
    lines.append("")
    return lines, len(rows)


def render_seed_document(
    sections: list[Section],
    *,
    banner_title: str,
    generated_by: str = "generate_migration.py",
    truncate_note: list[str] | None = None,
    truncate: bool = True,
) -> tuple[str, dict[str, int]]:
    """Wrap pre-built `(spec, rows)` sections in a full seed-migration document.

    `truncate=True` prefixes a `TRUNCATE ... RESTART IDENTITY CASCADE` over
    every section's table (the pack is the single source of truth, so rows
    removed from YAML vanish from the DB). `truncate_note` is emitted as
    comment lines immediately before the TRUNCATE. `generated_by` names the
    generator module in the banner so the regenerate hint points at the right
    CLI.
    """
    counts: dict[str, int] = {}
    lines: list[str] = [
        "-- ============================================================================",
        f"-- {banner_title}",
        f"-- Generated by backend/services/content_packs/{generated_by}",
        "-- DO NOT EDIT MANUALLY. Re-run the generator to regenerate.",
        "-- ============================================================================",
        "",
        "BEGIN;",
        "",
    ]
    if truncate:
        truncate_targets = ", ".join(spec.name for spec, _ in sections)
        if truncate_note:
            lines.extend(truncate_note)
        lines.append(f"TRUNCATE TABLE {truncate_targets} RESTART IDENTITY CASCADE;")
        lines.append("")
    for spec, rows in sections:
        section_lines, count = render_section(spec, rows)
        lines.extend(section_lines)
        counts[spec.name] = count
    lines.append("COMMIT;")
    lines.append("")
    return "\n".join(lines), counts


__all__ = ["Section", "emit_insert", "render_section", "render_seed_document"]
