"""Pydantic models for the per-simulation world map feature.

This module owns the contract between:
  * ForgeMapService (Python, builds geometry via shapely)
  * fn_apply_map_geometry (Postgres, atomic persistence — see migration 236)
  * The /api/v1/public/simulations/{id}/map endpoint (Phase 4)

Per the project Postgres-first principle (memory `feedback_postgres_first.md`):
the Python service ONLY constructs geometry — every UPDATE/INSERT lives in
fn_apply_map_geometry. These models describe the data shape that crosses the
Python ↔ Postgres boundary.
"""

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

# ── Generator presets ─────────────────────────────────────────────────────────
# Free text in the database (no CHECK constraint by design — adding a preset
# does not require a migration). Pydantic Literal validates allowed values at
# the API layer. Add a new preset here AND register a generator function in
# ForgeMapService._PRESET_REGISTRY.

MapGeneratorPreset = Literal[
    "medieval_walled",
    "modern_grid",
    "radial_capital",
    "coastal_port",
    "underground_station",
]


# ── Geometry payload (Python → Postgres via fn_apply_map_geometry) ───────────


class CityGeometryPatch(BaseModel):
    """Per-city map_center coordinates produced by the generator."""

    id: UUID
    map_center_lat: float
    map_center_lng: float


class ZoneGeometryPatch(BaseModel):
    """Per-zone polygon (GeoJSON Polygon) produced by the generator."""

    id: UUID
    geojson: dict[str, Any] = Field(
        description="GeoJSON Polygon — {'type': 'Polygon', 'coordinates': [[[lng, lat], ...]]}",
    )


class StreetGeometryInsert(BaseModel):
    """A new street row generated for a city.

    Streets are full-replacement: the SQL function DELETEs all existing streets
    for the simulation, then INSERTs these. IDs must be deterministically
    pre-generated by the Python service (uuid5 from sim_id + street index)
    so `buildings.street_id` references resolve consistently.
    """

    id: UUID
    city_id: UUID
    zone_id: UUID | None = None
    name: str | None = None
    street_type: Literal["arterial", "secondary", "tertiary", "alley"]
    length_km: float
    geojson: dict[str, Any] = Field(
        description="GeoJSON LineString — {'type': 'LineString', 'coordinates': [[lng, lat], [lng, lat], ...]}",
    )


class BuildingGeometryPatch(BaseModel):
    """Per-building point + nearest-street linkage produced by the generator."""

    id: UUID
    geojson: dict[str, Any] = Field(
        description="GeoJSON Point — {'type': 'Point', 'coordinates': [lng, lat]}",
    )
    street_id: UUID | None = None


class MapGeometryPayload(BaseModel):
    """The complete payload handed to fn_apply_map_geometry as a jsonb.

    Field names must match the jsonb keys the SQL function expects (see
    `supabase/migrations/20260510130000_236_fn_apply_map_geometry.sql`).
    """

    cities: list[CityGeometryPatch] = Field(default_factory=list)
    zones: list[ZoneGeometryPatch] = Field(default_factory=list)
    streets: list[StreetGeometryInsert] = Field(default_factory=list)
    buildings: list[BuildingGeometryPatch] = Field(default_factory=list)


# ── Generator result ─────────────────────────────────────────────────────────


class MapGenerationResult(BaseModel):
    """Returned by ForgeMapService.generate_map (and the admin regen endpoint).

    Counts come straight from fn_apply_map_geometry's RETURNING jsonb, so they
    reflect actual DB state after the atomic write.
    """

    model_config = ConfigDict(from_attributes=True)

    simulation_id: UUID
    preset_used: MapGeneratorPreset
    seed_used: str
    geometry_version: int = Field(description="The new map_geometry_version after the bump.")

    cities_updated: int
    zones_updated: int
    streets_inserted: int
    buildings_updated: int
    lives_at_inserted: int

    duration_seconds: float = Field(
        description="Wall-clock time for the full generation including the SQL write.",
    )


# ── Admin regen request body ─────────────────────────────────────────────────


class MapRegenerateRequest(BaseModel):
    """Body for POST /api/v1/admin/simulations/{id}/map/regenerate."""

    seed: str | None = Field(
        default=None,
        description="Override the deterministic seed. Defaults to simulations.id::text.",
        max_length=255,
    )
    preset: MapGeneratorPreset | None = Field(
        default=None,
        description="Override the generator preset. Defaults to simulations.map_generator_preset, "
        "falling back to a theme-based default in the service.",
    )


# ── Public API response types (Phase 4) ──────────────────────────────────────
# These are returned by GET /api/v1/public/simulations/{slug_or_id}/map.
# Geometry rows come from the Template (via source_template_id JOIN); live
# overlays (zone stability) come from the Instance. Agent home positions are
# resolved client-side by joining home_building_id against the buildings list.


class WorldMapCity(BaseModel):
    """A city within the simulation's geometry (one or more per sim)."""

    id: UUID
    name: str
    map_center_lat: float | None = None
    map_center_lng: float | None = None
    map_default_zoom: int | None = None


class WorldMapZone(BaseModel):
    """A zone polygon with optional live-overlay stability props.

    `geojson` is NULL until ForgeMapService has produced geometry.
    `stability` and `stability_label` come from the Instance's
    mv_zone_stability row when available — both are NULL if no overlay row
    exists (e.g. for a freshly-created sim before the view's first refresh).
    """

    id: UUID
    name: str
    zone_type: str | None = None
    geojson: dict[str, Any] | None = None
    stability: float | None = None
    stability_label: str | None = None


class WorldMapStreet(BaseModel):
    """A generated street as GeoJSON LineString."""

    id: UUID
    name: str | None = None
    street_type: str | None = None
    length_km: float | None = None
    geojson: dict[str, Any] | None = None


class WorldMapBuilding(BaseModel):
    """A building point + zone/street linkage for the map layer."""

    id: UUID
    name: str
    building_type: str | None = None
    geojson: dict[str, Any] | None = None
    street_id: UUID | None = None
    zone_id: UUID | None = None


class WorldMapAgentMarker(BaseModel):
    """An agent's home-position marker.

    The frontend looks up `home_building_id` against the buildings list to get
    the actual coordinate. Agents without a `lives_at` relation are omitted.
    """

    agent_id: UUID
    name: str
    home_building_id: UUID | None = None


class WorldMapThemeHints(BaseModel):
    """Narrow projection of forge_themes used by the MapLibre paint config.

    All fields are nullable so a sim without a generated theme still returns
    a valid (empty) hints block — the frontend falls back to its default
    design tokens.
    """

    color_primary: str | None = None
    color_surface: str | None = None
    color_border: str | None = None
    color_danger: str | None = None
    color_success: str | None = None
    color_text: str | None = None
    font_heading: str | None = None
    font_body: str | None = None


class WorldMapResponse(BaseModel):
    """Complete world map payload for one simulation (single round-trip).

    `geometry_source_id` is the Template's id when this is a Game-Instance,
    otherwise equals `simulation_id`. Frontend can use
    `(geometry_source_id, geometry_version)` as a stable cache key — the live
    overlay (stability) always comes from the Instance.
    """

    simulation_id: UUID
    simulation_slug: str
    is_game_instance: bool
    geometry_source_id: UUID
    geometry_version: int

    cities: list[WorldMapCity] = Field(default_factory=list)
    zones: list[WorldMapZone] = Field(default_factory=list)
    streets: list[WorldMapStreet] = Field(default_factory=list)
    buildings: list[WorldMapBuilding] = Field(default_factory=list)
    agent_markers: list[WorldMapAgentMarker] = Field(default_factory=list)

    theme_hints: WorldMapThemeHints = Field(default_factory=WorldMapThemeHints)
