/**
 * /terms — Terms of Service
 *
 * Required by Meta/Instagram API.
 */

import { msg } from '@lit/localize';
import { html } from 'lit';

import type { ContentPageData } from '../content-types.js';

export function getTermsPage(): ContentPageData {
  return {
    type: 'perspective',
    slug: 'terms',

    seo: {
      title: [msg('Terms of Service')],
      description: msg(
        'Terms of service for metaverse.center – rules of engagement for the Bureau of Multiverse Observation.',
      ),
      canonical: '/terms',
    },

    hero: {
      title: msg('Terms of Service'),
      subtitle: msg('Rules of engagement'),
    },

    breadcrumbs: [
      { name: 'Home', url: 'https://metaverse.center/' },
      { name: 'Terms of Service', url: 'https://metaverse.center/terms' },
    ],

    sections: [
      {
        id: 'acceptance',
        tocLabel: msg('Acceptance'),
        number: '01',
        title: msg('Acceptance of Terms'),
        content: html`
          <p>${msg('By accessing or using metaverse.center ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Platform.')}</p>
          <p>${msg('The Platform is operated by Ing. Mag. Matthias Leihs, BSc, based in Austria. These terms are governed by Austrian law and EU regulations.')}</p>
          <p>${msg('Last updated: March 19, 2026.')}</p>
        `,
      },
      {
        id: 'service',
        tocLabel: msg('The Service'),
        number: '02',
        title: msg('Description of Service'),
        content: html`
          <p>${msg('metaverse.center is a multiplayer worldbuilding and strategy platform. Users can create AI-powered simulations, interact with AI-generated characters, participate in competitive epochs, and connect their worlds into a multiverse.')}</p>
          <p>${msg('The Platform is provided "as is" and "as available." We reserve the right to modify, suspend, or discontinue any part of the service at any time without notice.')}</p>
        `,
      },
      {
        id: 'accounts',
        tocLabel: msg('Accounts'),
        number: '03',
        title: msg('User Accounts'),
        content: html`
          <p>${msg('You must register an account to create simulations or participate in competitive features. You are responsible for maintaining the security of your account credentials.')}</p>
          <p>${msg('You must be at least 16 years old to create an account (in compliance with GDPR requirements for minors).')}</p>
          <p>${msg('One account per person. Accounts may not be shared, sold, or transferred.')}</p>
        `,
      },
      {
        id: 'content',
        tocLabel: msg('Content'),
        number: '04',
        title: msg('User Content & Ownership'),
        content: html`
          <p><strong>${msg('Your content.')}</strong> ${msg('You retain ownership of all content you create on the Platform – simulations, agent configurations, lore, events, and other creative works. The Platform does not claim ownership of user-generated content.')}</p>
          <p><strong>${msg('License grant.')}</strong> ${msg('By creating content on the Platform, you grant metaverse.center a non-exclusive, worldwide license to display, store, and process your content for the purpose of operating the service. This includes generating AI responses based on your content (e.g., agent chat, chronicles) and displaying your public simulations to other users.')}</p>
          <p><strong>${msg('AI-generated content.')}</strong> ${msg('Content generated by AI (agent dialogue, chronicles, images, social media posts) is generated using your creative direction but produced by AI models. You may use AI-generated content from your simulations for personal and commercial purposes.')}</p>
          <p><strong>${msg('Public content.')}</strong> ${msg('Simulations marked as public are visible to all users and search engines. Public simulation data (names, descriptions, agent profiles, chronicles) may appear in search results and on the Platform\u2019s public pages.')}</p>
        `,
      },
      {
        id: 'conduct',
        tocLabel: msg('Conduct'),
        number: '05',
        title: msg('Acceptable Use'),
        content: html`
          <p>${msg('You agree not to:')}</p>
          <p>${msg('\u2013 Use the Platform to create content that promotes violence, hatred, or discrimination against individuals or groups.')}</p>
          <p>${msg('\u2013 Attempt to bypass security measures, access other users\u2019 accounts, or exploit vulnerabilities.')}</p>
          <p>${msg('\u2013 Use automated tools (bots, scrapers) to access the Platform without permission.')}</p>
          <p>${msg('\u2013 Upload malicious content, malware, or phishing materials.')}</p>
          <p>${msg('\u2013 Impersonate other users or misrepresent your identity.')}</p>
          <p>${msg('Violation of these terms may result in account suspension or termination.')}</p>
        `,
      },
      {
        id: 'competition',
        tocLabel: msg('Competition'),
        number: '06',
        title: msg('Competitive Play (Epochs)'),
        content: html`
          <p>${msg('Competitive epochs are time-limited matches between simulations. By entering an epoch, you agree to the match rules and scoring system as described in the How to Play guide.')}</p>
          <p>${msg('Game instances created for epochs are temporary clones of your simulation, normalized for fair competition. Your original simulation is never modified by competitive play.')}</p>
          <p>${msg('There is no monetary prize or reward for winning epochs. Rankings are for entertainment purposes only.')}</p>
        `,
      },
      {
        id: 'social-media',
        tocLabel: msg('Social Media'),
        number: '07',
        title: msg('Instagram & Social Media'),
        content: html`
          <p>${msg('The Platform operates an Instagram account (@bureau.of.impossible.geography) that publishes AI-generated content derived from user simulations.')}</p>
          <p>${msg('Published content is AI-generated fiction based on simulation data. All posts include an AI disclosure. No personally identifiable user data is included in social media posts.')}</p>
          <p>${msg('If your simulation\u2019s content is featured in a social media post and you wish it removed, contact us at privacy@metaverse.center.')}</p>
        `,
      },
      {
        id: 'liability',
        tocLabel: msg('Liability'),
        number: '08',
        title: msg('Limitation of Liability'),
        content: html`
          <p>${msg('The Platform is provided for entertainment and creative purposes. To the maximum extent permitted by applicable law:')}</p>
          <p>${msg('\u2013 We are not liable for any indirect, incidental, or consequential damages arising from your use of the Platform.')}</p>
          <p>${msg('\u2013 We are not responsible for AI-generated content that may be inaccurate, offensive, or inappropriate despite our moderation efforts.')}</p>
          <p>${msg('\u2013 We do not guarantee uninterrupted availability of the service.')}</p>
          <p>${msg('Nothing in these terms excludes liability that cannot be excluded under Austrian or EU law.')}</p>
        `,
      },
      {
        id: 'termination',
        tocLabel: msg('Termination'),
        number: '09',
        title: msg('Termination'),
        content: html`
          <p>${msg('You may delete your account at any time. Upon deletion, your personal data will be removed within 30 days as described in our Privacy Policy.')}</p>
          <p>${msg('We may suspend or terminate accounts that violate these terms, with or without notice.')}</p>
        `,
      },
      {
        id: 'changes',
        tocLabel: msg('Changes'),
        number: '10',
        title: msg('Changes to These Terms'),
        content: html`
          <p>${msg('We may update these terms from time to time. Significant changes will be communicated via email or platform notification. Continued use of the Platform after changes constitutes acceptance of the updated terms.')}</p>
          <p>${msg('For questions about these terms, contact: legal@metaverse.center.')}</p>
        `,
      },
    ],

    faqs: [],
    ctas: [],

    structuredData: {},
  };
}
