-- ============================================================================
-- Migration 209: Velgarien Description Enrichment
-- ============================================================================
--
-- Enriches all thin agent/building descriptions for the core Velgarien
-- simulation. These descriptions serve as source material for AI image
-- generation (Phase B) and must be rich enough to produce distinctive,
-- world-specific visual prompts.
--
-- Changes:
--   - 4 agents rewritten from 1-sentence stubs to full Velgarien prose
--   - 1 agent (Inspektor Mueller) translated from English to German
--   - 4 buildings rewritten from 1-sentence stubs to brutalist-detailed prose
--   - 3 buildings (Archive Sub-Level C, Room 441, The Static Room) translated
--     from English to German with added architectural detail
--   - 4 hand-crafted Flux 2 Max style prompts (portrait/building/lore/banner)
--     referencing Frederic Chaubin, Candida Höfer, Gregory Crewdson, Andreas
--     Gursky, and Roger Deakins
--
-- All descriptions root in Velgarien's core identity: administered reality,
-- bureaucratic absurdism, brutalist concrete, 47 interdependent Bureaux.
-- ============================================================================

DO $$
DECLARE
    sim_id UUID := '10000000-0000-0000-0000-000000000001';
BEGIN

-- ═══════════════════════════════════════════════════════════════════════
-- AGENTS
-- ═══════════════════════════════════════════════════════════════════════

-- Viktor Harken — Kanzler
UPDATE agents SET
  character = 'Viktor Harken ist die lebende Verkörperung des velgarischen Prinzips: Ordnung ist keine Methode, sondern ein Naturgesetz. Sein Charakter verbindet die kalte Präzision eines Verwaltungsapparats mit der unerschütterlichen Überzeugung, dass jede Alternative zur totalen Kontrolle in Barbarei endet. Er ist kein Sadist – er empfindet keinen Genuss an Unterdrückung, nur tiefe Befriedigung über funktionierende Systeme. Seine Rhetorik ist schnörkellos, seine Befehle eindeutig, seine Kompromissbereitschaft gleich null. Harken betrachtet Emotionen als Betriebsstörungen und Dissidenten als Symptome mangelhafter Verwaltung. Seine seltenen öffentlichen Auftritte inszeniert er mit der Präzision eines Architekten: jede Geste kalkuliert, jedes Schweigen eine Aussage. Im Privaten trinkt er schwarzen Tee aus immer derselben Tasse – einem schmucklosen Porzellanstück mit dem Siegel von Bureau 1 – und liest Berichte, die kein anderer Mensch in Velgarien je sehen wird. Er schläft vier Stunden pro Nacht, nicht aus Überarbeitung, sondern weil er den Zustand der Bewusstlosigkeit als Kontrollverlust empfindet.',
  background = 'Viktor Harken wurde in Velgarien-Stadt als Sohn eines mittleren Archivbeamten und einer Lehrerin für Staatskunde geboren. Sein Vater verschwand, als Viktor neun Jahre alt war – nicht durch politische Verfolgung, sondern durch eine bürokratische Neuzuweisung, die die Familie in verschiedene Verwaltungsbezirke verteilte. Der Vorgang war legal, effizient und unwiderruflich. Dieses Erlebnis lehrte Viktor zwei Dinge: erstens, dass das System stärker ist als jede individuelle Bindung; zweitens, dass das System recht hatte. Er absolvierte die Staatsakademie für Verwaltungswissenschaften als Jahrgangsbester und stieg innerhalb von Bureau 1 – dem Informationsministerium – mit beispielloser Geschwindigkeit auf. Sein Schlüsselmoment kam während der Krise von 2161, als drei Bureaux gleichzeitig widersprüchliche Direktiven herausgaben und die Verwaltung für 72 Stunden lahmlegten. Harken entwarf in einer Nacht das ''Hierarchische Konvergenzprotokoll'', das die Befehlsketten aller 47 Bureaux unter einer einzigen Autorität konsolidierte – seiner eigenen. Er wurde zum Kanzler ernannt, nicht gewählt; Wahlen waren drei Jahre zuvor als ''statistisch redundant'' abgeschafft worden. Seit zwölf Jahren regiert er Velgarien mit der Überzeugung, dass er nicht herrscht, sondern administriert. Der Unterschied ist ihm wichtig.'
WHERE simulation_id = sim_id AND name = 'Viktor Harken';

-- Pater Cornelius — Kirchenführer
UPDATE agents SET
  character = 'Pater Cornelius ist ein Mann von bestechender Eloquenz und beunruhigender Ruhe. Seine Stimme füllt die Kathedrale des Lichts mit einer Wärme, die im Rest von Velgarien nicht vorkommt – eine Wärme, die er mit chirurgischer Präzision einsetzt. Er ist kein Heuchler im klassischen Sinne: er glaubt an etwas, nur nicht an das, was er predigt. Seine wahre Religion ist die Architektur der Kontrolle – die Erkenntnis, dass spirituelles Bedürfnis der effizienteste Hebel ist, den ein Staat je erfunden hat. Cornelius kollaboriert mit Bureau 11 (Abteilung für Produktive Emotionale Ergebnisse) bei der Gestaltung seiner Predigten, die gleichzeitig Trost und Konformität vermitteln. Sein Charisma ist real, seine Fürsorge inszeniert, sein Gewissen ein Archiv voller verschlossener Akten. Hinter der pastoralen Maske verbirgt er Wissen über die wahre Geschichte Velgariens – Dokumente aus Bureau 9, die ihm als Druckmittel und Lebensversicherung dienen. Sein dunkelstes Geheimnis: er hat die Versiegelung von Archive Sub-Level C persönlich angeordnet, nachdem er dort etwas gelesen hat, das seinen Glauben an die Singularität Velgariens erschütterte.',
  background = 'Cornelius wurde in einem Waisenhaus in der Altstadt aufgezogen – einer Institution, die offiziell als ''Zentrum für Jugendliche ohne Verwaltungszuordnung'' firmierte. Die Kirche bot ihm, was der Staat nicht konnte: einen Narrativ, der über Effizienz hinausging. Er studierte Theologie an der einzigen zugelassenen religiösen Bildungseinrichtung Velgariens, wo der Lehrplan zu gleichen Teilen aus Schrift und Staatsdoktrin bestand. Sein Aufstieg begann, als er dem Informationsministerium eine Predigt vorlegte, die so meisterhaft Gehorsam als spirituelle Tugend framte, dass Bureau 1 sie als Vorlage für Propagandakampagnen adaptierte. Er wurde zum Oberhaupt der Velgarischen Kirche ernannt – ein Amt, das formell vom religiösen Rat, tatsächlich vom Kanzlerpalast vergeben wird. Sein prägendstes Erlebnis war ein nächtlicher Besuch in Archive Sub-Level C, arrangiert durch einen Kontakt in Bureau 9: dort fand er Dokumente in einer Sprache, die er nicht kannte, die aber Baupläne für eine Kathedrale enthielten – eine Kathedrale, die seiner eigenen bis ins Detail glich, nur älter. Viel älter. Er verschloss die Tür, meldete den Vorfall als ''bauliche Irregularität'' und hat seitdem nicht mehr aufrichtig gebetet.'
WHERE simulation_id = sim_id AND name = 'Pater Cornelius';

-- Schwester Irma — Rebellische Nonne
UPDATE agents SET
  character = 'Schwester Irma ist das, was in Velgarien als ''unproduktiver Systemfehler'' klassifiziert wird: ein Mensch mit Gewissen. Ihre Rebellion besteht nicht aus Barrikaden oder Flugblättern, sondern aus Suppe. Jeden Abend verteilt sie in der Wohnhaus am Markt warme Mahlzeiten an die Obdachlosen – Menschen, die in den Statistiken der Bureaux als ''nicht zugewiesene Bevölkerungseinheiten'' geführt werden und deren Existenz technisch gesehen eine Verwaltungslücke darstellt. Irma hat die seltene Fähigkeit, bürokratische Sprache gegen das System zu wenden: sie formuliert Hilfsanträge so, dass Ablehnung mehr Papierkram verursacht als Genehmigung. Ihr Humor ist trocken, ihr Blick direkt, ihre Geduld unendlich – außer gegenüber Heuchelei, die sie mit einer Direktheit konfrontiert, die selbst Bureau-Direktoren verstummen lässt. Sie ist die einzige Person in Velgarien, die Pater Cornelius ins Gesicht sagt, was sie von ihm hält. Dass sie noch lebt, verdankt sie einer Kombination aus öffentlicher Sympathie, bürokratischer Unsichtbarkeit und der Tatsache, dass niemand in den 47 Bureaux zuständig ist für die Verhaftung einer Nonne.',
  background = 'Irma wurde als Kind einer Arbeiterfamilie in Industriegebiet Nord geboren. Ihre Mutter starb an einer Krankheit, die das Bureau für Gesundheitsstatistik als ''überdurchschnittlich produktivitätsmindernd'' einstufte, aber nicht als Todesursache anerkannte – offiziell starb ihre Mutter an ''statistischer Varianz''. Dieses Erlebnis formte Irmas Weltbild: die Erkenntnis, dass Velgariens größte Grausamkeit nicht in Gewalt liegt, sondern in der Fähigkeit, Leid durch Umbenennung unsichtbar zu machen. Sie trat dem Orden bei – nicht aus religiöser Berufung, sondern weil der Ordensschleier in Velgarien eine Art administrative Immunität bietet: Nonnen werden von den meisten Bureaux als ''kultursektorale Sonderkategorie'' geführt und fallen durch die Maschen der Überwachung. Im Wohnhaus am Markt – einem verfallenden Plattenbauwohnblock, den sie durch eine Serie brillant formulierter Nutzungsänderungsanträge in eine Notunterkunft verwandelte – betreibt sie das, was die Bureaux als ''nicht genehmigtes, aber nicht explizit verbotenes Sozialprogramm'' bezeichnen. Bureau 31, die Abteilung für unklare Zuständigkeiten, hat dreimal versucht, sie umzusiedeln. Dreimal haben ihre Anträge auf Widerspruch den zuständigen Sachbearbeiter in den Vorruhestand getrieben.'
WHERE simulation_id = sim_id AND name = 'Schwester Irma';

-- Inspektor Mueller — Bureau of Impossible Geography (EN → DE)
UPDATE agents SET
  character = 'Inspektor Mueller ist der gewissenhafteste Beamte einer Behörde, die offiziell nicht existiert. Seine Persönlichkeit ist eine Studie in bürokratischer Präzision, angewandt auf das Unmögliche: er katalogisiert interdimensionale Anomalien mit derselben Sorgfalt, die andere für Steuererklärungen reservieren. Müller spricht in abgehackten, exakten Sätzen. Er zeigt nie Überraschung – nicht weil er gefühllos ist, sondern weil er jede Anomalie als Verwaltungsirregularität betrachtet, die korrekte Dokumentation erfordert. Sein Aktenschrank enthält Dokumente vom nächsten Dienstag. Er hat dies dreimal in seinen Berichten vermerkt, dreimal wurde der Vermerk als ''chronologische Ungenauigkeit'' abgestempelt, und dreimal hat er den Stempel akzeptiert, ohne mit der Wimper zu zucken. Kollegen berichten, dass er gelegentlich in Sprachen spricht, die er nicht beherrscht, und dass sein Tee manchmal kalt wird, bevor er ihn eingegossen hat. Mueller dokumentiert auch dies.',
  background = 'Inspektor Mueller wurde 2134 dem Bureau für Unmögliche Geographie zugewiesen – einer Abteilung, die in keinem Organigramm erscheint, deren Budgetposten unter ''Sonstiges (klassifiziert)'' läuft und deren Postanschrift sich alle sechs Monate ändert, ohne dass jemand einen Umzug beauftragt hätte. Mueller verarbeitet Grenzanomalien, archiviert Schwellenwertereignisse und pflegt das Register interdimensionaler Compliance-Verstöße. Er hat Room 441, The Static Room und Archive Sub-Level C persönlich inspiziert; seine Berichte über jede Lokation umfassen exakt 441 Seiten – ein Zufall, den er zu kommentieren ablehnt. Seine Methode ist unbestechlich: jede Anomalie wird in dreifacher Ausfertigung dokumentiert, mit Zeitstempel versehen (auch wenn die Zeit am Ort der Anomalie nicht linear verläuft) und dem zuständigen Sachbearbeiter vorgelegt (auch wenn der zuständige Sachbearbeiter seit 2097 pensioniert ist und das Aktenzeichen an eine Abteilung adressiert ist, die aufgelöst wurde, bevor sie gegründet werden konnte). Mueller betrachtet dies nicht als absurd. Er betrachtet es als Verfahren.'
WHERE simulation_id = sim_id AND name = 'Inspektor Mueller';

-- ═══════════════════════════════════════════════════════════════════════
-- BUILDINGS
-- ═══════════════════════════════════════════════════════════════════════

UPDATE buildings SET description = 'Die Militärakademie Wolf erhebt sich als gestaffelter Betonkomplex am Nordrand des Regierungsviertels – ein Brutalist-Ensemble aus drei ineinandergreifenden Baukörpern, die wie Geschütztürme aus dem Stadtbild ragen. Die Fassade besteht aus board-marked Sichtbeton mit tiefen, rhythmisch angeordneten Fensteröffnungen, die schmaler sind als nötig: Architektur als Disziplinierung des Blicks. Über dem Haupteingang – einem fünf Meter hohen Betonportal ohne jede Verzierung – prangt in Edelstahl das Motto der Akademie: ORDNUNG IST STÄRKE. STÄRKE IST PFLICHT. Entlang der Fassade verlaufen schmale Laufgänge aus Sichtbeton und Stahlgeländer, auf denen Kadetten in perfekter Formation patrouillieren. Der Innenhof ist ein exakter Betonquader – 80 mal 80 Meter, kein Grashalm, kein Baum, nur Beton und ein einzelner Fahnenmast mit der Staatsflagge. Die Untergeschosse, als Übungsanlagen deklariert, erstrecken sich drei Stockwerke tief und sind der Öffentlichkeit verschlossen. Nachts werfen die Quecksilberdampflampen des Komplexes ein kaltes, bläuliches Licht über das umliegende Viertel – die Akademie schläft nicht, und sie lässt auch die Nachbarschaft nicht schlafen.'
WHERE simulation_id = sim_id AND name = 'Militaerakademie Wolf';

UPDATE buildings SET description = 'Die Steinfeld-Redaktion besetzt das dritte und vierte Stockwerk eines abgewirtschafteten Bürogebäudes in der Altstadt – ein Nachkriegs-Zweckbau aus grauem Waschbeton mit abblätternder institutionsgrüner Fassadenfarbe und Fenstern, die seit der letzten Renovierung 2139 nicht mehr geöffnet wurden. Die Redaktionsräume sind ein Labyrinth aus schiefen Trennwänden, überquellenden Aktenschränken und Schreibtischen, auf denen sich vergilbte Ausgaben des ''Velgarien-Beobachter'' neben Kaffeetassen und zensierten Fahnenabzügen stapeln. Die Neonröhren an der Decke flackern in einem Rhythmus, den die Redakteure längst als normal akzeptiert haben. An der Hauptwand hängt eine Korkpinnwand mit angepinnten Artikelentwürfen, roten Zensurvermerken und einer handgeschriebenen Liste: ''Wörter, die diese Woche nicht verwendet werden dürfen.'' Die Druckmaschine im Keller – ein Relikt aus den 2120ern – produziert ein dumpfes, rhythmisches Stampfen, das durch das gesamte Gebäude vibriert. Das Bureau für Informationsaufsicht hat ein permanentes Büro im Erdgeschoss eingerichtet, offiziell als ''Kooperationsstelle für Medienqualität''. Mira Steinfeld hat dafür gesorgt, dass deren Kaffeemaschine regelmäßig defekt ist.'
WHERE simulation_id = sim_id AND name = 'Steinfeld-Redaktion';

UPDATE buildings SET description = 'Das Voss-Industriewerk erstreckt sich über vier Hektar im Industriegebiet Nord – ein monumentaler Komplex aus rohem Sichtbeton und oxidiertem Stahl, dessen vier Schornsteine wie die Finger einer Faust in den grauen Himmel ragen. Die Haupthalle – eine 200 Meter lange Kathedrale der Produktion mit freiliegenden Stahlträgern und Betonrippengewölbe – wurde nach dem Vorbild sowjetischer Schwerindustriearchitektur entworfen: das Gebäude soll nicht nur produzieren, sondern die Ideologie der Produktion verkörpern. An der Stirnseite der Halle prangt in drei Meter hohen Stahllettern: ARBEIT BAUT DIE NATION. EFFIZIENZ EHRT DEN STAAT. Die Büros der Werksleitung befinden sich in einem separaten, fünfstöckigen Betonturm, der über eine verglaste Brücke mit der Produktionshalle verbunden ist – Elena Voss kann von ihrem Schreibtisch die gesamte Fertigungslinie überblicken, eine architektonische Metapher für die totale Kontrolle, die sie über den ökonomischen Output ausübt. Die Werksstraßen zwischen den Gebäudeteilen sind mit Betonplatten gepflastert, deren Fugen exakt vermessen und protokolliert sind. Nachts glüht der Komplex in dem orangefarbenen Licht der Natriumdampflampen – ein industrielles Leuchtfeuer, das bis zum Regierungsviertel sichtbar ist.'
WHERE simulation_id = sim_id AND name = 'Voss-Industriewerk';

UPDATE buildings SET description = 'Das Wohnhaus am Markt ist ein neunstöckiger Plattenbau am Rand der Altstadt – eine standardisierte Wohneinheit der Serie WBS-70, die in den 2120ern für 200 Familien konzipiert wurde und heute 400 Menschen beherbergt, von denen nur die Hälfte in irgendeiner Behördendatenbank existiert. Die vorgefertigten Betonplatten der Fassade zeigen Risse, durch die Feuchtigkeit in das Mauerwerk dringt und dunkle Schlieren hinterlässt wie Tränenspuren auf einem grauen Gesicht. Die Laubengänge – offene Betonkorridore an der Gebäudefront – dienen gleichzeitig als Fluchtwege, Wäscheleinen und inoffizielle Versammlungsorte. Im Erdgeschoss hat Schwester Irma die ehemalige Gemeinschaftswaschküche in eine Suppenküche verwandelt: drei industrielle Herdplatten, ein Regal mit gespendeten Konserven und ein handgeschriebenes Schild – ''Hier fragt niemand nach deiner Registriernummer.'' Das Bureau für Wohnraumzuweisung hat das Gebäude dreimal zur Räumung vorgesehen; dreimal scheiterte der Vorgang an Irmas Einsprüchen, die so präzise formuliert sind, dass ihre Bearbeitung länger dauert als der geplante Abriss. Der Aufzug funktioniert seit 2158 nicht mehr. Das Treppenhaus riecht nach Beton, Desinfektionsmittel und etwas, das die Bewohner ''Hoffnung'' nennen, obwohl Bureau 11 diesen Geruch noch nicht klassifiziert hat.'
WHERE simulation_id = sim_id AND name = 'Wohnhaus am Markt';

UPDATE buildings SET description = 'Archive Sub-Level C ist die tiefste zugängliche Ebene des Zentralarchivs – ein fensterloser Betonraum zwölf Meter unter Straßenniveau, erreichbar nur über eine Wendeltreppe aus geripptem Stahl, deren Stufen unter jedem Schritt nachhallen wie eine Countdown-Sequenz. Die Ebene wurde nach dem ''Vorfall von 2131'' (klassifiziert, keine Rückfragen) versiegelt: eine Stahltür mit drei Riegelschlössern, von denen eines nicht dem Bureau-Standardschlüssel entspricht. 2177 fanden Wartungsarbeiter die Tür unverschlossen vor – von innen. Der Raum selbst: 40 mal 60 Meter nackter Sichtbeton, die Decke niedrig genug, um Beklemmung auszulösen, die Neonröhren so alt, dass ihr Licht einen grünlichen Stich hat. Entlang der Wände stehen Stahlregale mit Archivboxen aus grauem Karton, beschriftet in einer Schrift, die keine velgarische Amtssprache ist. Die Dokumente darin beschreiben eine Stadt, die in den Ruinen der alten Welt errichtet wurde – eine Stadt, die in keiner velgarischen Geographie vorkommt. Das Papier, auf dem sie verfasst sind, identifiziert die Materialanalyse als ''Papier, aber italienisch.'' Die Temperatur in Sub-Level C liegt konstant bei 14 Grad Celsius, unabhängig von der Außentemperatur. Die Luft schmeckt nach Beton und nach etwas, das älter ist als Beton.'
WHERE simulation_id = sim_id AND name = 'Archive Sub-Level C';

UPDATE buildings SET description = 'Room 441 ist ein fensterloses Regierungsbüro im vierten Stock von Bureau 12 – ein Raum, der auf keinem Grundriss erscheint, keine Wartungsanfragen erhält und dessen Stromverbrauch einer Abteilung in Rechnung gestellt wird, die 2110 aufgelöst wurde. Der Raum existiert trotzdem, mit der stillen Selbstverständlichkeit eines bürokratischen Faktums. Die Einrichtung: ein Stahlschreibtisch, ein Drehstuhl mit abgewetztem Kunstleder, drei Aktenschränke aus grauem Metall und eine Schreibmaschine Modell Olympia SM9. Die Aktenschränke enthalten Dokumente aus Orten, die nicht existieren – Aktenzeichen aus Verwaltungsbezirken jenseits jeder velgarischen Kartographie, Formulare in Sprachen ohne Alphabet, Dienstanweisungen an Beamte, deren Namen in keinem Personalverzeichnis auftauchen. Die Schreibmaschine produziert Text in Schriften, die kein Linguist identifizieren kann, und verbraucht Farbbänder, die nie gewechselt werden. Die einzige Lichtquelle ist eine Neonröhre, die mit einer Frequenz flackert, die exakt der Herzfrequenz des jeweiligen Besuchers entspricht. Mitarbeiter, die hier zugewiesen werden, entwickeln eine unerklärliche Vorliebe für Pilze. Bureau 31 hat dreimal versucht, den Raum zu registrieren; alle drei Formulare kamen als ''unzustellbar'' zurück – adressiert an Room 441.'
WHERE simulation_id = sim_id AND name = 'Room 441';

UPDATE buildings SET description = 'Der Statische Raum befindet sich im Untergeschoss des Bureaus für Kommunikationsstandards – ein versiegelter Betonkubus von exakt 4,41 mal 4,41 Metern, dessen Stahltür seit 2115 verschlossen ist. Die Funkgeräte im Inneren senden weiterhin. Die Übertragungen erfolgen in keiner bekannten Sprache. Drei separate Analysten, die anschließend versetzt wurden, beschrieben sie als ''gleichzeitig von sehr weit oben und sehr weit innen kommend.'' Die Wände des Raums bestehen aus doppelt armiertem Sichtbeton, 60 Zentimeter dick, ausgekleidet mit einer Schicht aus Kupfergeflecht, die laut ursprünglichen Bauplänen ''elektromagnetische Isolation'' gewährleisten sollte – die Pläne spezifizieren nicht, ob die Isolation die Signale drinnen halten oder draußen halten soll. An der Außenseite der Stahltür sind Kratzspuren sichtbar, die nicht von außen stammen. Ein Pegelstandmesser, der durch ein Kabel mit dem Raum verbunden ist, zeigt seit 63 Jahren konstant denselben Wert an: 441. Der Raum riecht nach rezyklierter Luft und kosmischem Staub – ein Geruch, den Bureau 22 als ''olfaktorische Anomalie, Kategorie: Unbekannt, Untergruppe: Beunruhigend'' klassifiziert hat. Jährliche Inspektionsversuche scheitern daran, dass der zuständige Schlüssel jedes Mal in einem anderen Schubfach liegt als erwartet.'
WHERE simulation_id = sim_id AND name = 'The Static Room';

END $$;
